version: '3.5'
services: 
    airstrip:
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: goreload .
        env_file: .env.local
        links:
            - postgres
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - ./:/build
    postgres:
        container_name: airstrip_db
        hostname: postgres
        environment: 
            - POSTGRES_USER=airstrip
            - POSTGRES_DB=airstrip
            - POSTGRES_PASSWORD=postgres
        image: 'postgres:alpine'
        ports: 
            - '5432:5432'
        restart: always
        volumes:
            - "./db:/var/lib/postgresql/data"
