version: '3.8'
services: 
    airstrip:
        container_name: airstrip
        build:
            context: .
            dockerfile: Dockerfile.dev
        command: goreload --buildArgs -buildvcs=false --path .
        volumes:
            - ./:/build
            - ./db:/build/db
