FROM golang:alpine
RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates
RUN apk add --virtual build-dependencies build-base gcc

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=1 \
    GOOS=linux \
    GOARCH=amd64

# Move to working directory /build
WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# RUN go get github.com/acoshift/goreload

# Copy the code into the container
COPY . .

EXPOSE $PORT

# Run test
# RUN go test ./...
