version: '3.5'
services: 
    airstrip:
        container_name: "airstrip-core"
        build: .
        env_file: .env
        links:
            - postgres
        volumes:
            - ./:/go/src/github.com/Donnie/Airstrip
    postgres:
        container_name: "airstrip-db"
        environment: 
            - POSTGRES_USER=airstrip
            - POSTGRES_DB=airstrip
            - POSTGRES_PASSWORD=postgres
        image: 'postgres:alpine'
        ports: 
            - '5432:5432'
        restart: always
        volumes:
          - "./db:/var/lib/postgresql/data"
